# What: The main orchestration file. It defines our services: backend, postgres, and redis. It sets up networking so they can communicate, defines persistent volumes for data, and maps ports.
# Why: Docker Compose allows us to define and run our entire multi-service application with a single command (docker-compose up). It manages the lifecycle of all our containers, making local development much simpler.

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app   # Mount local backend code into the container
    env_file:
      - .env
    depends_on:
      - postgres
      - redis


  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data:
