# What: The main orchestration file. It defines our services: backend, postgres, and redis. It sets up networking so they can communicate, defines persistent volumes for data, and maps ports.
# Why: Docker Compose allows us to define and run our entire multi-service application with a single command (docker-compose up). It manages the lifecycle of all our containers, making local development much simpler.

version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - localstack


  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"  # Main gateway port
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack_data:/var/lib/localstack
    privileged: true

  
  celery_worker:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    command: celery -A app.workers.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - backend
      - redis
      - postgres

  flower:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    command: celery -A app.workers.celery_app flower --port=5555
    volumes:
      - ./backend:/app
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis


volumes:
  postgres_data:
  redis_data:
  localstack_data: